name = "vig-sync"
main = "scripts/sync-nba26.js"
compatibility_date = "2025-01-20"

# Sync NBA games every 3 hours
[triggers]
crons = ["0 */3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "vig-db"
database_id = "abd188fa-f8a2-4f4e-8802-4ac89e50bd37"

[vars]
THE_RUNDOWN_API_KEY = "1f8078b504msh2dab2e95ae91a37p1f30cdjsncbb1bc069dca"
